
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GenerateJWTForAAPAndLaunchAndWaitJobTemplateWithSecureBodyParameters {
    /**
    * Label: Job template name/ID, type: entry
    */
    String aap_job_name
    /**
    * Label: EC-AnsibleTower Plugin Configuration, type: entry
    */
    String aap_plugin_configuration
    /**
    * Label: Job status polling interval, type: entry
    */
    String checkInterval
    /**
    * Label: Depend on Ansible Tower job result?, type: checkbox
    */
    boolean dependOnResult

    static GenerateJWTForAAPAndLaunchAndWaitJobTemplateWithSecureBodyParameters initParameters(StepParameters sp) {
        GenerateJWTForAAPAndLaunchAndWaitJobTemplateWithSecureBodyParameters parameters = new GenerateJWTForAAPAndLaunchAndWaitJobTemplateWithSecureBodyParameters()

        def aap_job_name = sp.getRequiredParameter('aap_job_name').value
        parameters.aap_job_name = aap_job_name

        def aap_plugin_configuration = sp.getRequiredParameter('aap_plugin_configuration').value
        parameters.aap_plugin_configuration = aap_plugin_configuration

        def checkInterval = sp.getParameter('checkInterval').value
        parameters.checkInterval = checkInterval

        def dependOnResult = sp.getParameter('dependOnResult').value == "true"
        parameters.dependOnResult = dependOnResult

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 4157207e48b9d41e5c1c706a98bec61a ===
