
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetAuthorizedTokenAndRunStepParameters {
    /**
    * Label: Shell of Command To Run, type: entry
    */
    String shellOfStepCommandToRun
    /**
    * Label: Command To Run, type: textarea
    */
    String stepCommandToRun

    static GetAuthorizedTokenAndRunStepParameters initParameters(StepParameters sp) {
        GetAuthorizedTokenAndRunStepParameters parameters = new GetAuthorizedTokenAndRunStepParameters()

        def shellOfStepCommandToRun = sp.getParameter('shellOfStepCommandToRun').value
        parameters.shellOfStepCommandToRun = shellOfStepCommandToRun

        def stepCommandToRun = sp.getRequiredParameter('stepCommandToRun').value
        parameters.stepCommandToRun = stepCommandToRun

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 7e66bf93900774420145f36907aa30bf ===
