
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetCdroCredentialAndRunStepParameters {
    /**
    * Label: Secret Path, type: entry
    */
    String secretPath
    /**
    * Label: Shell of Command To Run, type: entry
    */
    String shellOfStepCommandToRun
    /**
    * Label: Command To Run, type: textarea
    */
    String stepCommandToRun

    static GetCdroCredentialAndRunStepParameters initParameters(StepParameters sp) {
        GetCdroCredentialAndRunStepParameters parameters = new GetCdroCredentialAndRunStepParameters()

        def secretPath = sp.getRequiredParameter('secretPath').value
        parameters.secretPath = secretPath

        def shellOfStepCommandToRun = sp.getParameter('shellOfStepCommandToRun').value
        parameters.shellOfStepCommandToRun = shellOfStepCommandToRun

        def stepCommandToRun = sp.getRequiredParameter('stepCommandToRun').value
        parameters.stepCommandToRun = stepCommandToRun

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 6b1f5302fc5e128edf4573623aacb3c2 ===
