
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetCdroCredentialAndRunStepParameters {
    /**
    * Label: Secret Path, type: entry
    */
    String secretPath
    /**
    * Label: Shell of Command To Run, type: entry
    */
    String shellOfStepCommandToRun
    /**
    * Label: Command To Run, type: textarea
    */
    String stepCommandToRun

    static GetCdroCredentialAndRunStepParameters initParameters(StepParameters sp) {
        GetCdroCredentialAndRunStepParameters parameters = new GetCdroCredentialAndRunStepParameters()

        def secretPath = sp.getRequiredParameter('secretPath').value
        parameters.secretPath = secretPath

        def shellOfStepCommandToRun = sp.getParameter('shellOfStepCommandToRun').value
        parameters.shellOfStepCommandToRun = shellOfStepCommandToRun  ?: 'ec-groovy'

        def stepCommandToRun = sp.getRequiredParameter('stepCommandToRun').value
        parameters.stepCommandToRun = stepCommandToRun

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 08bee426d50b5e1c7be5a1fe46ee6eed ===
