
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class IssueJwtAndStoreInPropertyParameters {
    /**
    * Label: Property Path, type: entry
    */
    String propertyPath

    static IssueJwtAndStoreInPropertyParameters initParameters(StepParameters sp) {
        IssueJwtAndStoreInPropertyParameters parameters = new IssueJwtAndStoreInPropertyParameters()

        def propertyPath = sp.getRequiredParameter('propertyPath').value
        parameters.propertyPath = propertyPath  ?: '/myPipelineRuntime/jwtToken'

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 987330edccd7cbcb76e7bd0f8ab9cca0 ===
