
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class IssueJwtAndRunStepParameters {
    /**
    * Label: Shell of Command To Run, type: entry
    */
    String shellOfStepCommandToRun
    /**
    * Label: Command To Run, type: textarea
    */
    String stepCommandToRun

    static IssueJwtAndRunStepParameters initParameters(StepParameters sp) {
        IssueJwtAndRunStepParameters parameters = new IssueJwtAndRunStepParameters()

        def shellOfStepCommandToRun = sp.getParameter('shellOfStepCommandToRun').value
        parameters.shellOfStepCommandToRun = shellOfStepCommandToRun

        def stepCommandToRun = sp.getRequiredParameter('stepCommandToRun').value
        parameters.stepCommandToRun = stepCommandToRun

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 1ca64d1fbe530b0661d539524bd51afe ===
