
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class UpdateCdroCredentialThroughJwtRequestParameters {
    /**
    * Label: Credential ProjectName, type: entry
    */
    String credentialProjectName
    /**
    * Label: Credential Name, type: entry
    */
    String credentialName
    /**
    * Label: Secret Path, type: entry
    */
    String secretPath

    static UpdateCdroCredentialThroughJwtRequestParameters initParameters(StepParameters sp) {
        UpdateCdroCredentialThroughJwtRequestParameters parameters = new UpdateCdroCredentialThroughJwtRequestParameters()

        def credentialProjectName = sp.getRequiredParameter('credentialProjectName').value
        parameters.credentialProjectName = credentialProjectName

        def credentialName = sp.getRequiredParameter('credentialName').value
        parameters.credentialName = credentialName

        def secretPath = sp.getRequiredParameter('secretPath').value
        parameters.secretPath = secretPath

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 459b71ba3dc7a42352f56c59a9bf179e ===
